on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: hello ## lets you identify it in the workflow
        uses: ./
        with:
          myInput: 'Bernaaa'
      - name: output
        run: |
            echo ${{ steps.hello.outputs.memory }}
            echo "total memory sucessfully output"